name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: "27.1"
            rebar3: "3.24.0"
            os: ubuntu-latest

          - otp: "26.2.5"
            rebar3: "3.24.0"
            os: ubuntu-latest

    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}

      - name: Check out
        uses: actions/checkout@v3

      - name: Compile
        run: rebar3 compile

      - name: Run unit tests
        run: rebar3 eunit